pipeline:
  name: dev_pipeline
  identifier: dev_pipeline
  projectIdentifier: SonarQube_Test_Project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: Multi_Branch_Connector
        build: <+input>
  stages:
    - stage:
        name: demo_stage_1
        identifier: demo_stage_1
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: demo_step_1
                  identifier: demo_step_1
                  spec:
                    shell: Sh
                    command: |-
                      echo "Demo step 1"
                      echo <+pipeline.branch>
                      echo <+pipeline.sequenceId>
              - step:
                  name: demo_step_2
                  identifier: demo_step_2
                  template:
                    templateRef: account.Simple_Run_Shell_Template
                    versionLabel: Version1
